name: Build Web-App

on:
  push:
    branches:
      - trunk

concurrency:
  cancel-in-progress: true
  group: build-app

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build and Test
    strategy:
      fail-fast: true
      matrix:
        action: ["build", "test"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn

      - name: Cache
        id: yarn-unplugged
        uses: actions/cache@v3
        with:
          path: .yarn/unplugged
          key: ${{ runner.os }}-yarn-unplugged-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-unplugged

      - name: Install Deps
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' && steps.yarn-unplugged.outputs.cache-hit != 'true' }}
        run: yarn --immutable --check-cache

      - name: Cache
        if: ${{ matrix.action == 'build' }}
        id: next-cache
        uses: actions/cache@v3
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-output
          restore-keys: ${{ runner.os }}-nextjs-output

      - name: ${{ matrix.action }}
        run: yarn ${{ matrix.action }}

      - uses: actions/upload-artifact@v3
        if: ${{ matrix.action == 'build' }}
        with:
          name: app-output
          path: .next

  deploy:
    needs:
      - build_and_test
    runs-on: ubuntu-latest
    name: Deploy from Artifacts
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/download-artifact@v3
        with:
          name: app-output
          path: .next
      - uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_SECRET }} # Required
          zeit-token: ${{ secrets.VERCEL_SECRET }}
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} #Required
          vercel-args: "--prod"
