name: Build Web-App

on: push

concurrency:
  cancel-in-progress: true
  group: build-app

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        action: ["build", "test"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn

      - name: Cache
        id: yarn-unplugged
        uses: actions/cache@v3
        with:
          path: .yarn/unplugged
          key: ${{ runner.os }}-yarn-unplugged-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-unplugged

      - name: Install Deps
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' && steps.yarn-unplugged.outputs.cache-hit != 'true' }}
        run: yarn --immutable --check-cache

      - name: Cache
        if: ${{ matrix.action == 'build' }}
        id: next-cache
        uses: actions/cache@v3
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-output
          restore-keys: ${{ runner.os }}-nextjs-output

      - name: Build
        run: yarn ${{ matrix.action }}
